// ============================================================================
// DATABASE SCHEMA — guided build
//
// Docs to read first:
//   - Column types (text/integer/boolean/jsonb/timestamp/uuid/date):
//     https://orm.drizzle.team/docs/column-types/pg
//   - Primary keys, unique constraints, foreign keys (.references()):
//     https://orm.drizzle.team/docs/indexes-constraints
//
// Pattern: each table is `export const tableName = pgTable("table_name", { ...columns })`.
// Each column is `propertyName: columnType("snake_case_db_name")` plus chained
// modifiers like `.notNull()`, `.unique()`, `.default(...)`.
// ============================================================================

import {
  boolean,
  date,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import type { Goal } from "@/lib/content/goals";

// Plain TS unions (not DB types) — used with `.$type<...>()` below to
// restrict what a text column is allowed to hold, at the TypeScript level.
export type ComfortLevel = "photo_only" | "simple_video" | "confident_video";
export type MediaType = "photo" | "video";

// ----------------------------------------------------------------------------
// TABLE 1: businesses — one row per restaurant owner's onboarding profile
// ----------------------------------------------------------------------------
export const businesses = pgTable("businesses", {
  // WORKED EXAMPLE — id: a uuid primary key, auto-generated by Postgres if
  // not provided on insert.
  id: uuid("id").primaryKey().defaultRandom(),

  // WORKED EXAMPLE — clerkUserId: required, and no two businesses can share
  // one (one business per Clerk-authenticated user).
  clerkUserId: text("clerk_user_id").notNull().unique(),

  // TODO: add the rest of the columns below. Field list (from the plan):
  //   - category: text, required, defaults to "restaurant"
  category: text("category").notNull().default("restaurant"),
  //   - name: text, optional (nullable until onboarding fills it in)
  //   - cuisine: text, optional
  //   - goal: text, optional — use `.$type<Goal>()` so only valid Goal
  //     values type-check (see the goals.ts import above)
  //   - signatureDishes: jsonb holding a string[], default empty array
  //     — use `.$type<string[]>()`
  //   - specials: jsonb holding `{ label: string; description?: string }[]`,
  //     default empty array
  //   - targetAudience: text, optional
  //   - brandTone: text, optional
  //   - contentComfortLevel: text, optional — `.$type<ComfortLevel>()`
  //   - postingFrequency: integer, optional (1-3, validated later by Zod —
  //     the database itself doesn't need to enforce the range)
  //   - socialHandles: jsonb holding
  //     `{ instagram?: string; tiktok?: string; facebook?: string }`,
  //     default `{}`
  //   - address: text, optional
  //   - phone: text, optional
  //   - onboardingCompletedAt: timestamp with timezone, optional (stays
  //     null until onboarding finishes — its presence IS the "is onboarded"
  //     check we'll use later)
  //   - createdAt: timestamp with timezone, required, defaults to now
  //   - updatedAt: timestamp with timezone, required, defaults to now
});

// ----------------------------------------------------------------------------
// TABLE 2: contentFormats — the library of content "types" we can suggest
// (seeded with real rows later — this table's rows don't change at runtime)
// ----------------------------------------------------------------------------
export const contentFormats = pgTable("content_formats", {
  // TODO: columns needed (no worked example this time — same patterns as above):
  //   - id: text primary key (NOT uuid — we want readable ids we write by
  //     hand in the seed file, e.g. "signature_dish_spotlight_video")
  //   - category: text, required, defaults to "restaurant"
  //   - name: text, required (the Spanish display name)
  //   - mediaType: text, required — `.$type<MediaType>()`
  //   - description: text, required (internal notes, not shown to users)
  //   - goalTags: jsonb holding `Goal[]`, required, default empty array
  //     (empty array = "suits every goal")
  //   - requiresComfortLevel: text, required — `.$type<ComfortLevel>()`
  //   - promptGuidance: text, required (extra context we'll feed to Claude)
  //   - active: boolean, required, defaults to true
  //   - createdAt: timestamp with timezone, required, defaults to now
});

// ----------------------------------------------------------------------------
// TABLE 3: suggestions — one row per generated weekly card a business sees
// ----------------------------------------------------------------------------
export const suggestions = pgTable(
  "suggestions",
  {
    // TODO: columns needed:
    //   - id: uuid primary key, auto-generated
    //   - businessId: uuid, required — a FOREIGN KEY to businesses.id.
    //     Pattern: `.references(() => businesses.id, { onDelete: "cascade" })`
    //     `onDelete: "cascade"` means: if the business row is deleted, its
    //     suggestions get deleted automatically too.
    //   - formatId: text, required — foreign key to contentFormats.id
    //     (no onDelete needed here)
    //   - weekStartDate: date, required (the Monday this card belongs to)
    //   - position: integer, required (1, 2, or 3 — "Video 1 de 3")
    //   - mediaType: text, required — `.$type<MediaType>()` (copied from
    //     the format at generation time)
    //   - targetDurationSeconds: integer, optional (video only)
    //   - shotList: jsonb holding
    //     `{ order: number; description: string; durationSeconds?: number }[]`,
    //     required
    //   - editingNotes: jsonb, optional/nullable, holding
    //     `{ cuts?: string; music?: string; textOverlays?: { atSecond: number; text: string }[] } | null`
    //     (null for photo formats)
    //   - caption: text, required
    //   - status: text, required, defaults to "pending" —
    //     `.$type<"pending" | "ready" | "failed">()`
    //   - generationError: text, optional (only set if Claude generation fails)
    //   - isRegeneration: boolean, required, defaults to false
    //   - regeneratedFromSuggestionId: uuid, optional (points back to the
    //     card this one replaced, if any — no .references() needed, it's
    //     optional/self-referencing, plain uuid column is fine for MVP)
    //   - rejectedFormatIds: jsonb holding `string[]`, required, default
    //     empty array
    //   - createdAt / updatedAt: timestamp with timezone, required, default now
  },
  // TODO: a table-level constraint so one business can't have two cards in
  // the same slot (same week + same position). Pattern (see the Indexes &
  // Constraints doc link above, "Multi-column" unique):
  //   (t) => [unique().on(t.businessId, t.weekStartDate, t.position)]
  (t) => [],
);
